apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-mongo-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
